name: Manual
on:
  workflow_dispatch:
    inputs:
      cmdline:
        description: 'Commandline parameters'
        required: false
        default: -h
jobs:
  hello_oas2sw_job:
    runs-on: ubuntu-latest
    name: A job to run custom action
    steps:
      - name: Run custom action
        uses: synfinme/oas2sw@v0.2
        with:
          cmdline: ${{ github.event.inputs.cmdline }}
  hello_oas2sw_job2:
    runs-on: ubuntu-latest
    name: A job to run custom action (again)
    steps:
      - name: Run custom action
        uses: synfinme/oas2sw@v0.2
        with:
          cmdline: ${{ github.event.inputs.cmdline }}
